# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-07 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_post_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='decription',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
