# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-07 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20161106_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
